version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0 -p 5050
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 8091:5050
    env_file:
      - ./.env.dev
